# test.yml
#
# Copyright (C) 2022 ViliusSutkus89.com
#
# Documenter is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: test
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/test.yml'

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

env:
  applicationId: com.viliussutkus89.documenter

jobs:
  releaseBuild:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Generate ephemeral keystore
        run: keytool -genkey -noprompt -alias alias1 -dname "CN=$applicationId.ephemeral, OU=EphemeralSignatures, O=ViliusSutkus89.com, L=Kaunas, S=Kaunas, C=LT" -keystore app/$applicationId.ephemeral.jks -keypass 123456 -keyalg RSA -keysize 4096 -validity 1 -storepass 123456

      - run: ./gradlew assembleRelease lintRelease -Ptest_build
        env:
          SIGNING_KEYFILE: ${{env.applicationId}}.ephemeral.jks
          SIGNING_PASS: 123456
          SIGNING_ALIAS: alias1

      - name: artifact release builds
        uses: actions/upload-artifact@v3
        with:
          name: APKs
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error

      - name: Artifact lint report
        uses: actions/upload-artifact@v3
        with:
          path: app/build/reports/lint-results-release.html
          name: lintResults
          if-no-files-found: error

  debugBuild:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - run: ./gradlew assembleDebug -Ptest_build

      # Needs to be tarballed, because regular artifacts and caches take forever
      - name: prepare app/build
        run: tar -cf app-build.tar app/build

      - name: artifact app/build
        uses: actions/upload-artifact@v3
        with:
          name: app-build.tar
          path: app-build.tar
          if-no-files-found: error

  test:
    needs: debugBuild
    # Only macos VMs are available with exposed CPU extensions to run hardware accelerated emulator
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        include:
          # Oldest provisionally supported API
          - arch: x86
            api-level: 16
            api-type-target: default
          # Oldest properly supported API
          - arch: x86
            api-level: 19
            api-type-target: default
          # Oldest 64 bit
          - arch: x86_64
            api-level: 21
            api-type-target: default
          # targetSdk
          - arch: x86_64
            api-level: 32
            api-type-target: google_apis
          # Latest image
          - arch: x86_64
            api-level: 33
            api-type-target: google_apis
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: AVD (Android Virtual Device) Cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: /Users/runner/avd-cache.tar
          key: avd-${{ matrix.arch }}-${{ matrix.api-level }}-${{ matrix.api-type-target }}-${{ secrets.CACHE_KEY_SUFFIX }}

      - run: tar -v -xf avd-cache.tar
        if: steps.avd-cache.outputs.cache-hit
        working-directory: /Users/runner

      - name: Create AVD and generate snapshot
        uses: reactivecircus/android-emulator-runner@v2
        if: ${{ ! steps.avd-cache.outputs.cache-hit }}
        with:
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          target: ${{ matrix.api-type-target }}
          sdcard-path-or-size: 1G
          disk-size: 8G
          script: echo "Generated AVD snapshot for caching."

      - run: tar -v -cf avd-cache.tar .android/adb* .android/avd/*
        working-directory: /Users/runner
        if: ${{ ! steps.avd-cache.outputs.cache-hit }}

      - name: Download app/build artifact
        uses: actions/download-artifact@v3
        with:
          name: app-build.tar
      - run: tar -xf app-build.tar

      - run: pip3 install adbPullAs

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          target: ${{ matrix.api-type-target }}
          sdcard-path-or-size: 1G
          disk-size: 8G
          script: |
            mkdir -p testResults/TestScreenshots
            adb logcat -c || true
            adb logcat > testResults/logcat.txt &

            adb shell screencap /data/local/tmp/beforeTests.png || true
            adb pull /data/local/tmp/beforeTests.png testResults/TestScreenshots/ || true

            ./gradlew connectedCheck || touch sorry_but_tests_are_failing
            # Depending on API version, TestScreenshots could be in any of these dirs

            adb pull /data/local/tmp/TestScreenshots testResults/TestScreenshots/ || true
            adbPullAs $applicationId /data/data/$applicationId/cache/TestScreenshots /data/user/0/$applicationId/cache/TestScreenshots /sdcard/Android/data/$applicationId/cache/TestScreenshots testResults/ || true

            adb shell screencap /data/local/tmp/afterTests.png || true
            adb pull /data/local/tmp/afterTests.png testResults/TestScreenshots/ || true

            mv app/build/reports/androidTests/connected testResults/
            mv app/build/outputs/androidTest-results testResults/

            test ! -f sorry_but_tests_are_failing

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: testResults-${{ matrix.api-level }}-${{ matrix.arch }}-${{ matrix.api-type-target }}
          path: testResults
          if-no-files-found: error
