# test.yml
#
# Copyright (C) 2022 ViliusSutkus89.com
#
# Documenter is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: test
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/test.yml'

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

env:
  applicationId: com.viliussutkus89.documenter

jobs:
  test:
    # Only macos VMs are available with exposed CPU extensions to run hardware accelerated emulator
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        include:
          # Oldest supported API
          - arch: x86
            api-level: 19
            api-type-target: default
          # Oldest x86_64 image
          - arch: x86_64
            api-level: 21
            api-type-target: default
          # Latest x86 image
          - arch: x86
            api-level: 30
            api-type-target: google_atd
          # Latest image
          - arch: x86_64
            api-level: 33
            api-type-target: google_apis
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: android-actions/setup-android@v2

      - run: pip install adbPullAs

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          target: ${{ matrix.api-type-target }}
          sdcard-path-or-size: 1G
          disk-size: 8G
          script: |
            mkdir -p testResults/TestScreenshots
            adb logcat -c || true
            adb logcat > testResults/logcat.txt &

            adb shell screencap /data/local/tmp/beforeTests.png || true
            adb pull /data/local/tmp/beforeTests.png testResults/TestScreenshots/ || true

            ./gradlew connectedCheck || touch sorry_but_tests_are_failing
            # Depending on API version, TestScreenshots could be in any of these dirs

            adb pull /data/local/tmp/TestScreenshots testResults/TestScreenshots/ || true
            adbPullAs $applicationId \
              /data/data/$applicationId/cache/TestScreenshots \
              /data/user/0/$applicationId/cache/TestScreenshots \
              /sdcard/Android/data/$applicationId/cache/TestScreenshots \
              testResults/ || true

            adb shell screencap /data/local/tmp/afterTests.png || true
            adb pull /data/local/tmp/afterTests.png testResults/TestScreenshots/ || true

            mv app/build/reports/androidTests/connected testResults/
            mv app/build/outputs/androidTest-results testResults/

            test ! -f sorry_but_tests_are_failing

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: testResults-${{ matrix.api-level }}-${{ matrix.arch }}-${{ matrix.api-type-target }}
          path: testResults
          if-no-files-found: error
