name: Instrumented Tests
run-name: Test on android-${{ inputs.api-level }} ${{ inputs.arch }} (${{ inputs.api-type-target }})
on:
  workflow_call:
    inputs:
      api-level:
        required: true
        type: string
      arch:
        required: true
        type: string
      api-type-target:
        required: true
        type: string
      applicationId:
        required: true
        type: string

jobs:
  instrumentedTests:
    # Only macos VMs are available with exposed CPU extensions to run hardware accelerated emulator
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v3

      # @TODO: remove --break-system-packages once python is sorted
      - run: pip3 install adbPullAs --break-system-packages

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
          api-level: ${{ inputs.api-level }}
          arch: ${{ inputs.arch }}
          target: ${{ inputs.api-type-target }}
          sdcard-path-or-size: 1G
          disk-size: 8G
          script: |
            mkdir -p testResults/screenshots
            adb logcat > testResults/logcat.txt &

            adb shell screencap /data/local/tmp/beforeTests.png
            adb pull /data/local/tmp/beforeTests.png testResults/screenshots/

            ./gradlew connectedCheck || touch sorry_but_tests_are_failing
            adb pull /sdcard/Pictures/screenshots testResults/ || true
            adbPullAs ${{ inputs.applicationId }} /data/data/${{ inputs.applicationId }}/cache/TestScreenshots /data/user/0/$applicationId/cache/TestScreenshots /sdcard/Android/data/${{ inputs.applicationId }}/cache/TestScreenshots testResults/ || true

            adb shell screencap /data/local/tmp/afterTests.png
            adb pull /data/local/tmp/afterTests.png testResults/screenshots/

            mv app/build/reports/androidTests/connected testResults/
            mv app/build/outputs/androidTest-results testResults/

            test ! -f sorry_but_tests_are_failing

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: testResults-${{ inputs.api-level }}-${{ inputs.arch }}-${{ inputs.api-type-target }}
          path: testResults
          if-no-files-found: error
